export const demoProfiles = {
  brand: [
    {
      id: "demo-brand-mori",
      role: "brand",
      display_name: "Mori Skin 森肌",
      is_demo: true,
      avatar_url: "assets/demo/brand-mori.svg",
      profile_data: {
        category: "美妝保養",
        bio: "專注敏感肌保養的台灣品牌，希望與重視真實使用感受的創作者長期合作。",
        platform: "Instagram、YouTube",
        collaboration: "付費合作、產品體驗",
        budget: "NT$ 8,000–20,000",
        creatorType: "美妝、生活風格",
        openings: "3",
        timeline: "長期招募",
        brief: "新品體驗、日常保養情境與真實使用心得，內容形式可共同討論。",
      },
    },
    {
      id: "demo-brand-hoom",
      role: "brand",
      display_name: "Hoom 好物所",
      is_demo: true,
      avatar_url: "assets/demo/brand-hoom.svg",
      profile_data: {
        category: "生活選物",
        bio: "讓日常空間更舒服的居家選物品牌，尋找有生活感與空間美感的內容夥伴。",
        platform: "Instagram、Threads",
        collaboration: "付費合作、聯名企劃",
        budget: "NT$ 6,000–15,000",
        creatorType: "居家、生活風格",
        openings: "5",
        timeline: "每月合作",
        brief: "以居家佈置、開箱與生活提案呈現產品如何融入真實日常。",
      },
    },
    {
      id: "demo-brand-oatday",
      role: "brand",
      display_name: "Oatday 燕麥日",
      is_demo: true,
      avatar_url: "assets/demo/brand-oatday.svg",
      profile_data: {
        category: "食品飲品",
        bio: "新世代植物飲品牌，募集健康生活、美食與運動領域的短影音創作者。",
        platform: "Instagram、TikTok、YouTube",
        collaboration: "付費合作、銷售分潤",
        budget: "NT$ 10,000–25,000",
        creatorType: "美食、運動、健康",
        openings: "8",
        timeline: "新品上市期間",
        brief: "希望以早餐、健身補給或創意飲品等自然情境介紹產品。",
      },
    },
    {
      id: "demo-brand-chainwave",
      role: "brand",
      display_name: "ChainWave 鏈浪",
      is_demo: true,
      avatar_url: "assets/demo/brand-chainwave.svg",
      profile_data: {
        category: "加密貨幣／Web3",
        bio: "提供台灣使用者容易理解的 Web3 教育內容與安全工具。",
        platform: "YouTube、X / Twitter、Podcast",
        collaboration: "付費合作、內容共創",
        budget: "NT$ 15,000–40,000",
        creatorType: "財經、科技、知識型",
        openings: "4",
        timeline: "季度合作",
        brief: "重視資訊正確、風險揭露與長期教育價值，不做短線喊單內容。",
      },
    },
    {
      id: "demo-brand-pawday",
      role: "brand",
      display_name: "Pawday 毛日子",
      is_demo: true,
      avatar_url: "assets/demo/brand-pawday.svg",
      profile_data: {
        category: "寵物",
        bio: "以透明成分與日常照護為核心的台灣寵物用品品牌。",
        platform: "Instagram、Facebook",
        collaboration: "互惠合作、付費合作",
        budget: "產品互惠–NT$ 12,000",
        creatorType: "犬貓、家庭生活",
        openings: "6",
        timeline: "長期招募",
        brief: "歡迎真實飼養經驗分享，寵物健康與安全永遠優先。",
      },
    },
    {
      id: "demo-brand-roam",
      role: "brand",
      display_name: "Roam 島旅",
      is_demo: true,
      avatar_url: "assets/demo/brand-roam.svg",
      profile_data: {
        category: "旅遊住宿",
        bio: "串連台灣在地旅宿與深度體驗，讓旅行回到人與地方的連結。",
        platform: "Instagram、YouTube、部落格",
        collaboration: "體驗交換、付費專案",
        budget: "NT$ 12,000–35,000",
        creatorType: "旅遊、攝影、親子",
        openings: "3",
        timeline: "依旅宿檔期",
        brief: "希望呈現在地故事、住宿細節與真實旅程，不以制式打卡為主。",
      },
    },
  ],
  creator: [
    {
      id: "demo-creator-yuna",
      role: "creator",
      display_name: "Yuna 日常選物",
      is_demo: true,
      avatar_url: "assets/demo/creator-yuna.webp",
      profile_data: {
        category: "生活風格",
        bio: "分享租屋佈置、日常選物與簡單生活，擅長自然光影與情境式短影音。",
        platform: "Instagram、Threads",
        followers: "38,200",
        engagement: "6.8%",
        audience: "24–34 歲女性",
        collaboration: "付費合作、長期大使",
        rate: "NT$ 9,000 起",
        location: "台北市",
        preferences: "偏好生活選物、居家與保養品牌，不接受博弈類合作。",
      },
    },
    {
      id: "demo-creator-mia",
      role: "creator",
      display_name: "Mia 保養研究室",
      is_demo: true,
      avatar_url: "assets/demo/creator-mia.webp",
      profile_data: {
        category: "美妝保養",
        bio: "成分導向的保養內容創作者，以清楚比較與長期實測建立受眾信任。",
        platform: "Instagram、YouTube",
        followers: "52,600",
        engagement: "8.2%",
        audience: "20–35 歲保養族群",
        collaboration: "付費評測、產品實測",
        rate: "NT$ 15,000 起",
        location: "新北市",
        preferences: "重視完整成分資訊與合理試用期，不接受未揭露廣告要求。",
      },
    },
    {
      id: "demo-creator-lily",
      role: "creator",
      display_name: "莉莉育兒生活",
      is_demo: true,
      avatar_url: "assets/demo/creator-lily.webp",
      profile_data: {
        category: "親子育兒",
        bio: "記錄雙寶家庭的真實日常，內容涵蓋親子用品、共讀與週末出遊。",
        platform: "Instagram、Facebook",
        followers: "29,400",
        engagement: "7.1%",
        audience: "25–40 歲家長",
        collaboration: "付費合作、親子體驗",
        rate: "NT$ 8,000 起",
        location: "桃園市",
        preferences: "以兒童安全與家庭實用性為優先，不做過度誇大內容。",
      },
    },
    {
      id: "demo-creator-kai",
      role: "creator",
      display_name: "Kai 週末出走",
      is_demo: true,
      avatar_url: "assets/demo/creator-kai.webp",
      profile_data: {
        category: "旅遊住宿",
        bio: "用完整影像故事介紹台灣小旅行、戶外體驗與有特色的地方旅宿。",
        platform: "YouTube、Instagram",
        followers: "71,000",
        engagement: "5.9%",
        audience: "22–38 歲旅遊族群",
        collaboration: "付費專案、旅宿體驗",
        rate: "NT$ 22,000 起",
        location: "台中市",
        preferences: "偏好有地方故事與永續理念的旅遊合作。",
      },
    },
    {
      id: "demo-creator-zoe",
      role: "creator",
      display_name: "Zoe 理財慢慢說",
      is_demo: true,
      avatar_url: "assets/demo/creator-zoe.webp",
      profile_data: {
        category: "財經投資",
        bio: "把複雜金融知識轉成容易理解的圖文與短影音，強調風險意識。",
        platform: "Instagram、Podcast、Threads",
        followers: "46,800",
        engagement: "6.3%",
        audience: "25–39 歲上班族",
        collaboration: "內容共創、付費合作",
        rate: "NT$ 18,000 起",
        location: "台北市",
        preferences: "接受合規金融教育與工具服務，不接受保證獲利或喊單合作。",
      },
    },
    {
      id: "demo-creator-anson",
      role: "creator",
      display_name: "Anson 科技生活",
      is_demo: true,
      avatar_url: "assets/demo/creator-anson.webp",
      profile_data: {
        category: "3C 科技",
        bio: "以實際使用情境評測手機、智慧家庭與效率工具。",
        platform: "YouTube、Instagram",
        followers: "84,300",
        engagement: "5.4%",
        audience: "20–40 歲科技使用者",
        collaboration: "付費評測、活動出席",
        rate: "NT$ 25,000 起",
        location: "台北市",
        preferences: "需要足夠測試時間，保留真實評論與優缺點說明。",
      },
    },
  ],
};

export function findDemoProfile(id, role) {
  return (demoProfiles[role] || []).find((profile) => profile.id === id) || null;
}
